#pragma once

namespace bp
{

enum MessageID
{
    MSG_BP_CONN_INSERT         = 4000,
    MSG_BP_BEFORE_CONN_DELETE  = 4001,
    MSG_BP_AFTER_CONN_DELETE   = 4002,
    MSG_BP_CONN_REBUILD        = 4003,

    MSG_BP_NODE_PROP_CHANGED   = 4004,

    MSG_BP_DISABLE_UPDATE_EVAL = 4005,
    MSG_BP_ENABLE_UPDATE_EVAL  = 4006,

    MSG_BP_SCENE_ROOT_TO_NEXT_LEVEL,
    MSG_BP_SCENE_ROOT_SEEK_TO_PREV_LEVEL,

}; // MessageID

}